### ISSUE TITLE
Milestones

### ISSUE THREAD

**Issue by spences10** [chingu-voyage4/grad.then#73]
# Lets talk about Milestones 🗿 

For accountability and our motivation let's get some milestones set up.

I made an attempt but need your input please. 🙏 

What are realistic milestones for us to start aiming for...

So far there is the following:

* app design
* main page
* mvp complete
* learn
* jobs
* event
* stories
* support

can we talk about what needs to go into them and dates on completion 

thanks

**Comment by mar-bi** [comment]
As we still far from completion of these milestones we can add one more (which is closer)
  - **app components** - we are going to finish them soon.
  - **user stories** - some of them has already incorporated in app design (we build this way because we expect some *user-app* interactions) and there will be more  

I thinks others are relevant. 
After completion of  the **app components** we can move directly to pages.

**Comment by mar-bi** [comment]
One more: 
- **responsive pages** :boom:

**Comment by mar-bi** [comment]
And maybe **app design** we can close. 
We did it, accepted and applied. 
What is going now is just *fine-tunning* :lipstick:  :smile:

**Comment by spences10** [comment]
>And maybe app design we can close.

☝️  this will complete when the https://github.com/chingu-voyage3/grad.then/issues/1 is closed

**Comment by mar-bi** [comment]
Ok, I've got it :grin:
